name: keyboard_actions
description: Now you can add features to the Android / iOS keyboard in a very simple way. 
version: 4.0.0
homepage: https://github.com/diegoveloper/
repository: https://github.com/diegoveloper/flutter_keyboard_actions/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
flutter: